Integrate jmaps script to toolbox

diff --git a/bin/jmaps b/bin/jmaps
--- a/bin/jmaps
+++ b/bin/jmaps
@@ -1,3 +1,4 @@
+#!/bin/bash
 # jmaps - creates java /tmp/perf-PID.map symbol maps for all java processes.
 #
 # This is a helper script that finds all running "java" processes, then executes
@@ -17,65 +18,73 @@
 # REQUIREMENTS:
 # Tune two environment settings below.
 #
-# 13-Feb-2015	Brendan Gregg	Created this.
+# 13-Feb-2015    Brendan Gregg    Created this.
 
-JAVA_HOME=/usr/lib/jvm/java-8-oracle
-AGENT_HOME=/usr/lib/jvm/perf-map-agent	# from https://github.com/jrudolph/perf-map-agent
+
+DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
+GRADLEDEV_TOOLBOX_DIR=$(dirname "$DIR")
+
+AGENT_HOME=$GRADLEDEV_TOOLBOX_DIR/perf-map-agent    # from https://github.com/jrudolph/perf-map-agent
+if [[ ! -e $AGENT_HOME/out/libperfmap.so ]]; then
+    cd $AGENT_HOME || { echo "perf-map-agent doesn't exist at $AGENT_HOME."; exit 1; }
+    cmake .
+    make
+fi
 
 if [[ "$USER" != root ]]; then
-	echo "ERROR: not root user? exiting..."
-	exit
+    echo "ERROR: not root user? exiting..."
+    exit
 fi
 
 if [[ ! -x $JAVA_HOME ]]; then
-	echo "ERROR: JAVA_HOME not set correctly; edit $0 and fix"
-	exit
+    echo "ERROR: JAVA_HOME not set correctly; edit $0 and fix"
+    exit
 fi
 
 if [[ ! -x $AGENT_HOME ]]; then
-	echo "ERROR: AGENT_HOME not set correctly; edit $0 and fix"
-	exit
+    echo "ERROR: AGENT_HOME not set correctly; edit $0 and fix"
+    exit
 fi
 
 # figure out where the agent files are:
 AGENT_OUT=""
 AGENT_JAR=""
 if [[ -e $AGENT_HOME/out/attach-main.jar ]]; then
-	AGENT_JAR=$AGENT_HOME/out/attach-main.jar
+    AGENT_JAR=$AGENT_HOME/out/attach-main.jar
 elif [[ -e $AGENT_HOME/attach-main.jar ]]; then
-	AGENT_JAR=$AGENT_HOME/attach-main.jar
+    AGENT_JAR=$AGENT_HOME/attach-main.jar
 fi
 if [[ -e $AGENT_HOME/out/libperfmap.so ]]; then
-	AGENT_OUT=$AGENT_HOME/out
+    AGENT_OUT=$AGENT_HOME/out
 elif [[ -e $AGENT_HOME/libperfmap.so ]]; then
-	AGENT_OUT=$AGENT_HOME
+    AGENT_OUT=$AGENT_HOME
 fi
 if [[ "$AGENT_OUT" == "" || "$AGENT_JAR" == "" ]]; then
-	echo "ERROR: Missing perf-map-agent files in $AGENT_HOME. Check installation."
-	exit
+    echo "ERROR: Missing perf-map-agent files in $AGENT_HOME. Check installation."
+    exit
 fi
 
 echo "Fetching maps for all java processes..."
 for pid in $(pgrep -x java); do
-	mapfile=/tmp/perf-$pid.map
-	[[ -e $mapfile ]] && rm $mapfile
-	cmd="cd $AGENT_OUT; $JAVA_HOME/bin/java -Xms32m -Xmx128m -cp $AGENT_JAR:$JAVA_HOME/lib/tools.jar net.virtualvoid.perf.AttachOnce $pid"
-echo $cmd
-	user=$(ps ho user -p $pid)
-	if [[ "$user" != root ]]; then
-		# make $user the username if it is a UID:
-		if [[ "$user" == [0-9]* ]]; then user=$(awk -F: '$3 == '$user' { print $1 }' /etc/passwd); fi
-		cmd="sudo -u $user sh -c '$cmd'"
-	fi
-	echo "Mapping PID $pid (user $user):"
-	time eval $cmd
-	if [[ -e "$mapfile" ]]; then
-		chown root $mapfile
-		chmod 666 $mapfile
-	else
-		echo "ERROR: $mapfile not created."
-	fi
-	echo
-	echo "wc(1): $(wc $mapfile)"
-	echo
+    mapfile=/tmp/perf-$pid.map
+    [[ -e $mapfile ]] && rm $mapfile
+    cmd="cd $AGENT_OUT; $JAVA_HOME/bin/java -Xms32m -Xmx128m -cp $AGENT_JAR:$JAVA_HOME/lib/tools.jar net.virtualvoid.perf.AttachOnce $pid"
+    echo $cmd
+    user=$(ps ho user -p $pid)
+    if [[ "$user" != root ]]; then
+        # make $user the username if it is a UID:
+        if [[ "$user" == [0-9]* ]]; then user=$(awk -F: '$3 == '$user' { print $1 }' /etc/passwd); fi
+        cmd="sudo -u $user sh -c '$cmd'"
+    fi
+    echo "Mapping PID $pid (user $user):"
+    time eval $cmd
+    if [[ -e "$mapfile" ]]; then
+        chown root $mapfile
+        chmod 666 $mapfile
+    else
+        echo "ERROR: $mapfile not created."
+    fi
+    echo
+    echo "wc(1): $(wc $mapfile)"
+    echo
 done
